services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4 
    container_name: elasticsearch
    environment:
      - path.repo=/usr/share/elasticsearch/snapshots
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - ELASTIC_PASSWORD=Ditiss_pass_2025
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    mem_limit: 3g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - /path/on/host/snapshots:/usr/share/elasticsearch/snapshots
    networks:
      - elk-net

  logstash:
    #build: ./logstash  # your custom logstash Dockerfile here
    image: docker.elastic.co/logstash/logstash:8.19.0
    container_name: logstash
    env_file:
      - ./aws.env 
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash/Cloud/sincedb:/usr/share/logstash/Cloud/sincedb
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/geoip/GeoLite2-City.mmdb:/usr/share/logstash/GeoLite2-City.mmdb
      - ./logstash/geoip/GeoLite2-ASN.mmdb:/usr/share/logstash/GeoLite2-ASN.mmdb
      - ./logstash/geoip/GeoLite2-Country.mmdb:/usr/share/logstash/GeoLite2-Country.mmdb
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logs/nginx-access.log:/var/log/nginx/access.log:ro
#      - ./logstash/Cloud/s3-logs/data:/usr/share/logstash/s3-logs
    networks:
      - elk-net

#  webserver:
#    image: nginx:latest
#    container_name: webserver
#    ports:
#      - "8080:80"
#    volumes:
      # Mount access log so Logstash can read it
#      - ./logs/nginx-access.log:/var/log/nginx/access.log
#      - ./logs/nginx-error.log:/var/log/nginx/error.log
#    command: [ "sh", "-c", "nginx -g 'daemon off;'" ]
#    networks:
#      - elk-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elk-net

volumes:
  esdata:

networks:
  elk-net:
    driver: bridge
